server:
  port: 9300

spring:
  application:
    name: mapflux-oauth
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/mapflux_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: 111111
    driver-class-name: org.postgresql.Driver


#mp 类型别名配置
mybatis-plus:
  mapper-locations: classpath:com/cq/szyk/mapfluxoauth/mapper/*.xml
  type-aliases-package: com.cq.szyk.mapfluxmodel.users

#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://mapflux:mapflux@127.0.0.1:9100/eureka