server:
  port: 9200

spring:
  application:
    name: mapflux-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://localhost:5432/mapflux_manager
    username: postgres
    password: 111111
    driver-class-name: org.postgresql.Driver
  #redis
  redis:
    database: 0
    host: 192.168.139.133
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 100000

#mp 类型别名配置
mybatis-plus:
  mapper-locations: classpath:com/cq/szyk/mapfluxuser/mapper/*.xml
  type-aliases-package: com.cq.szyk.mapfluxmodel.users

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    com.cq.szyk.mapfluxuser.mapper: debug
#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://mapflux:mapflux@127.0.0.1:9100/eureka

#eureka 负载均衡配置,使用最小并发服务器
mapflux-oauth:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule


#访问认证服务器常量配置
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: client
#      #获取token
#      access-token-uri: http://localhost:9300/oauth/token
#      #获取令牌
#      user-authorization-uri: http://localhost:9300/oauth/authorize
#    resource:
#      #验证token是否正确
#      token-info-uri: http://localhost:9300/oauth/check_token
